import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { rateLimit, clientIpFromHeaders } from "@/lib/rate-limit";
import { canUsePsirt, type OrgPlan } from "@/lib/constants/plans";

/**
 * Generates a security.txt file (RFC 9116) for an org that has enabled its
 * public security page. Customers can download it and host on their own
 * domain at /.well-known/security.txt.
 */
export async function GET(
  req: Request,
  ctx: { params: Promise<{ slug: string }> },
) {
  // 20 requests per IP per 10 minutes — legitimate tooling fetches security.txt
  // once per domain. Anything higher is either a crawler we want to throttle or
  // a slug-enumeration scanner.
  const ip = clientIpFromHeaders(req.headers);
  const gate = await rateLimit({
    endpoint: "security-txt",
    identifier: ip,
    limit: 20,
    windowMs: 10 * 60_000,
  });
  if (!gate.ok) {
    return new NextResponse("Too Many Requests", {
      status: 429,
      headers: {
        "Retry-After": String(gate.retryAfterSeconds ?? 60),
      },
    });
  }

  const { slug } = await ctx.params;
  const supabase = await createClient();

  const { data } = await supabase
    .from("organizations")
    .select(
      "name, slug, security_contact_email, security_policy, security_public_enabled, plan",
    )
    .eq("slug", slug)
    .eq("security_public_enabled", true)
    .single();

  if (!data) {
    return new NextResponse("Not found", { status: 404 });
  }

  // Plan gate: the PSIRT page is Business+. Hide it if the org isn't (e.g.
  // they enabled it then downgraded).
  const plan = ((data as { plan?: string }).plan ?? "free") as OrgPlan;
  if (!canUsePsirt(plan)) {
    return new NextResponse("Not found", { status: 404 });
  }

  const row = data as {
    name: string;
    slug: string;
    security_contact_email: string | null;
  };

  const origin = new URL(req.url).origin;
  const policyUrl = `${origin}/en/security/${row.slug}`;
  const expires = new Date();
  expires.setFullYear(expires.getFullYear() + 1);

  const lines = [
    `# Security policy for ${row.name}`,
    `# Generated by Seentrix — update fields below to match your infra`,
    ``,
  ];
  if (row.security_contact_email) {
    lines.push(`Contact: mailto:${row.security_contact_email}`);
  }
  lines.push(`Contact: ${policyUrl}`);
  lines.push(`Expires: ${expires.toISOString()}`);
  lines.push(`Preferred-Languages: en, de`);
  lines.push(`Policy: ${policyUrl}`);
  lines.push(``);
  const body = lines.join("\n");

  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="security.txt"`,
      "Cache-Control": "no-store",
    },
  });
}
