import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

/**
 * Generates a security.txt file (RFC 9116) for an org that has enabled its
 * public security page. Customers can download it and host on their own
 * domain at /.well-known/security.txt.
 */
export async function GET(
  req: Request,
  ctx: { params: Promise<{ slug: string }> },
) {
  const { slug } = await ctx.params;
  const supabase = await createClient();

  const { data } = await supabase
    .from("organizations")
    .select(
      "name, slug, security_contact_email, security_policy, security_public_enabled",
    )
    .eq("slug", slug)
    .eq("security_public_enabled", true)
    .single();

  if (!data) {
    return new NextResponse("Not found", { status: 404 });
  }

  const row = data as {
    name: string;
    slug: string;
    security_contact_email: string | null;
  };

  const origin = new URL(req.url).origin;
  const policyUrl = `${origin}/en/security/${row.slug}`;
  const expires = new Date();
  expires.setFullYear(expires.getFullYear() + 1);

  const lines = [
    `# Security policy for ${row.name}`,
    `# Generated by Seentrix — update fields below to match your infra`,
    ``,
  ];
  if (row.security_contact_email) {
    lines.push(`Contact: mailto:${row.security_contact_email}`);
  }
  lines.push(`Contact: ${policyUrl}`);
  lines.push(`Expires: ${expires.toISOString()}`);
  lines.push(`Preferred-Languages: en, de`);
  lines.push(`Policy: ${policyUrl}`);
  lines.push(``);
  const body = lines.join("\n");

  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="security.txt"`,
      "Cache-Control": "no-store",
    },
  });
}
