/* eslint-disable react/no-unescaped-entities */
import { Link } from "@/i18n/navigation";

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-xs text-muted-foreground">
        Last updated: {new Date().toISOString().slice(0, 10)}
      </p>

      <h2>1. Agreement to these Terms</h2>
      <p>
        These Terms of Service ("Terms") govern your access to and use of the
        Seentrix platform ("Service") operated by{" "}
        <strong>Seentrix Ltd</strong> ("we", "us", "Seentrix"), a private
        limited company registered in England and Wales with company number{" "}
        <strong>17169165</strong>, registered office at{" "}
        <strong>167-169 Great Portland Street, London, England, W1W 5PF, United Kingdom</strong>.
        By creating an account or using the Service, you agree to be bound by
        these Terms. If you do not agree, do not use the Service.
      </p>

      <h2>2. Service description</h2>
      <p>
        Seentrix is a compliance platform that helps manufacturers document,
        evidence, and maintain compliance with the EU Cyber Resilience Act
        (Regulation (EU) 2024/2847) and adjacent obligations. We provide
        workflows, templates, and storage — we do not provide legal advice.
        Any document generated by Seentrix is drafted from your inputs and
        must be reviewed by a qualified professional before use in a
        regulatory context.
      </p>

      <h2>3. Accounts and organisations</h2>
      <p>
        You must provide accurate information when creating an account.
        Administrators of an organisation are responsible for the actions
        of all members they invite, including ensuring every team member
        completes any mandatory training configured in the platform.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Upload malware, illegal content, or infringing material.</li>
        <li>
          Reverse-engineer, scrape, or attempt to gain unauthorised access
          to the Service or its infrastructure.
        </li>
        <li>
          Submit vulnerability reports through our public intake in bad
          faith (e.g. to harass another organisation or spam).
        </li>
        <li>Resell the Service without a written agreement.</li>
      </ul>

      <h2>5. Subscription and fees</h2>
      <p>
        Paid plans are billed through Stripe based on the pricing published
        at <Link href="/pricing">seentrix.com/pricing</Link>. Fees are
        non-refundable except where required by law. You may cancel at any
        time via the billing portal; cancellation takes effect at the end of
        the current billing period. Unpaid invoices past <strong>14</strong>{" "}
        days may result in suspension.
      </p>

      <h2>6. Your data</h2>
      <p>
        You retain all rights to the data you upload to Seentrix. You grant
        us a limited licence to process that data solely to operate and
        improve the Service as described in our{" "}
        <Link href="/legal/privacy">Privacy Policy</Link> and{" "}
        <Link href="/legal/dpa">Data Processing Agreement</Link>. We will not
        sell your data or use it for unrelated advertising.
      </p>

      <h2>7. Service availability and support</h2>
      <p>
        We aim to maintain high availability but do not guarantee uninterrupted
        service. Planned maintenance is announced by email to the address on
        file. Support channels and response targets are described in your
        plan.
      </p>

      <h2>8. Warranty disclaimer</h2>
      <p>
        The Service is provided "as is" and "as available" without warranties
        of any kind, express or implied, to the maximum extent permitted by
        law. Seentrix is not a substitute for legal advice; you are solely
        responsible for your regulatory compliance.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, Seentrix's aggregate liability
        arising out of or related to the Service is limited to the fees you
        paid for the Service in the twelve months preceding the claim. We
        are not liable for indirect, incidental, consequential, or punitive
        damages.
      </p>

      <h2>10. Termination</h2>
      <p>
        Either party may terminate this agreement at any time. Upon
        termination, you will retain access until the end of your current
        billing period. After termination, your data will be retained for
        a grace period as described in the Privacy Policy before deletion.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These Terms are governed by the laws of{" "}
        <strong>England and Wales</strong>, without regard to conflict-of-
        laws rules. Any dispute will be brought exclusively before the
        courts of <strong>London, England</strong>.
      </p>

      <h2>12. Changes to these Terms</h2>
      <p>
        We may update these Terms occasionally. Material changes will be
        notified to the email on file at least 30 days before they take
        effect. Continued use after the effective date constitutes
        acceptance.
      </p>

      <h2>13. Contact</h2>
      <p>
        Questions about these Terms? Contact{" "}
        <a href="mailto:support@seentrix.com">support@seentrix.com</a>.
      </p>
      <p className="mt-6 text-xs text-muted-foreground">
        Seentrix Ltd · Company number 17169165 · Registered in England and Wales ·
        167-169 Great Portland Street, London W1W 5PF, United Kingdom
      </p>
    </>
  );
}

export const metadata = { title: "Terms of Service" };
